"""Effort, automation and estimation engine (spec §23, §24, §25).

Deliberately **deterministic**: estimates are computed from the canonical model,
not generated by a model. An LLM that invents person-days is worse than useless
commercially, and the numbers must be reproducible and defensible in front of a
customer.

Every estimate reports the multipliers that produced it, so a reviewer can
challenge an input rather than the total.
"""
from __future__ import annotations

from dataclasses import asdict, dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional


class Automation(str, Enum):
    """How a work item gets done (spec §23)."""

    FULL = "FULL_AUTOMATION"          # machine executes
    AI_ASSISTED = "AI_ASSISTED"       # AI generates, human reviews
    HUMAN_DECISION = "HUMAN_DECISION" # AI recommends, authorised person decides
    MANUAL = "MANUAL"                 # human specialist required


#: Share of the work the platform removes, per automation class.
AUTOMATION_SAVING = {
    Automation.FULL: 0.90,
    Automation.AI_ASSISTED: 0.55,
    Automation.HUMAN_DECISION: 0.20,
    Automation.MANUAL: 0.0,
}

#: Baseline person-days for one unit of each work type, at nominal complexity.
#: These are the platform's published assumptions, not guarantees (§24).
BASELINE_DAYS = {
    "discovery_workshop": 2.0,
    "requirement": 0.25,
    "source_system": 3.0,
    "data_entity": 1.5,
    "pipeline": 2.5,
    "data_quality_rule": 0.3,
    "semantic_model": 4.0,
    "report": 1.5,
    "ml_model": 8.0,
    "application_screen": 2.0,
    "api_endpoint": 1.0,
    "integration": 4.0,
    "test_suite": 2.0,
    "environment": 3.0,
    "governance_control": 1.0,
}

#: Which automation class each work type falls into.
WORK_AUTOMATION = {
    "discovery_workshop": Automation.HUMAN_DECISION,
    "requirement": Automation.AI_ASSISTED,
    "source_system": Automation.AI_ASSISTED,
    "data_entity": Automation.AI_ASSISTED,
    "pipeline": Automation.AI_ASSISTED,
    "data_quality_rule": Automation.FULL,
    "semantic_model": Automation.AI_ASSISTED,
    "report": Automation.AI_ASSISTED,
    "ml_model": Automation.HUMAN_DECISION,
    "application_screen": Automation.AI_ASSISTED,
    "api_endpoint": Automation.AI_ASSISTED,
    "integration": Automation.HUMAN_DECISION,
    "test_suite": Automation.FULL,
    "environment": Automation.MANUAL,
    "governance_control": Automation.HUMAN_DECISION,
}

ROLE_FOR_WORK = {
    "discovery_workshop": "Business Analyst",
    "requirement": "Business Analyst",
    "source_system": "Data Engineer",
    "data_entity": "Data Architect",
    "pipeline": "Data Engineer",
    "data_quality_rule": "Data Engineer",
    "semantic_model": "BI Developer",
    "report": "BI Developer",
    "ml_model": "AI Engineer",
    "application_screen": "Application Developer",
    "api_endpoint": "Application Developer",
    "integration": "Solution Architect",
    "test_suite": "QA Engineer",
    "environment": "Platform Engineer",
    "governance_control": "Security Architect",
}


@dataclass
class Complexity:
    """Multipliers applied to the baseline (spec §25). 1.0 is nominal."""

    technical: float = 1.0
    data: float = 1.0
    integration: float = 1.0
    governance: float = 1.0
    environment: float = 1.0

    def factor(self) -> float:
        return (self.technical * self.data * self.integration
                * self.governance * self.environment)

    def to_dict(self) -> dict:
        d = asdict(self)
        d["combined"] = round(self.factor(), 3)
        return d


@dataclass
class WorkItem:
    """One estimable unit (spec §23)."""

    id: str
    title: str
    work_type: str
    quantity: int = 1
    complexity: Complexity = field(default_factory=Complexity)
    depends_on: List[str] = field(default_factory=list)
    owner: str = ""
    risk: str = "medium"

    @property
    def automation(self) -> Automation:
        return WORK_AUTOMATION.get(self.work_type, Automation.AI_ASSISTED)

    @property
    def role(self) -> str:
        return self.owner or ROLE_FOR_WORK.get(self.work_type, "Data Engineer")

    def manual_days(self) -> float:
        """Effort with no platform assistance — the comparison baseline."""
        return BASELINE_DAYS.get(self.work_type, 1.0) * self.quantity * self.complexity.factor()

    def estimate(self) -> "ItemEstimate":
        manual = self.manual_days()
        saving = AUTOMATION_SAVING[self.automation]
        automated = manual * saving
        remaining = manual - automated
        # Generated output still has to be reviewed; that review is real effort
        # and is never netted to zero (§23).
        review = automated * 0.18 if self.automation is not Automation.MANUAL else 0.0
        return ItemEstimate(
            item_id=self.id, title=self.title, work_type=self.work_type,
            role=self.role, automation=self.automation.value,
            manual_days=round(manual, 2),
            engineering_days=round(remaining, 2),
            review_days=round(review, 2),
            total_days=round(remaining + review, 2),
            saved_days=round(manual - (remaining + review), 2),
            complexity=self.complexity.to_dict(), risk=self.risk,
        )


@dataclass
class ItemEstimate:
    item_id: str
    title: str
    work_type: str
    role: str
    automation: str
    manual_days: float
    engineering_days: float
    review_days: float
    total_days: float
    saved_days: float
    complexity: dict
    risk: str

    def to_dict(self) -> dict:
        return asdict(self)


def estimate(items: List[WorkItem], contingency: float = 0.15,
             team_size: int = 5, working_days_per_week: int = 5) -> Dict[str, Any]:
    """Roll work items up into an estimate (spec §25).

    Returns effort, duration, role split, automation coverage and the critical
    path, together with the inputs used so the result can be challenged.
    """
    if not items:
        return {"ok": False, "reason": "No work items supplied.",
                "totals": {}, "items": [], "by_role": {}, "automation": {}}

    estimates = [i.estimate() for i in items]
    manual = sum(e.manual_days for e in estimates)
    total = sum(e.total_days for e in estimates)
    review = sum(e.review_days for e in estimates)
    saved = sum(e.saved_days for e in estimates)

    with_contingency = total * (1 + contingency)
    coverage = (saved / manual) if manual else 0.0

    by_role: Dict[str, float] = {}
    for e in estimates:
        by_role[e.role] = round(by_role.get(e.role, 0.0) + e.total_days, 2)

    by_automation: Dict[str, Dict[str, float]] = {}
    for e in estimates:
        slot = by_automation.setdefault(e.automation, {"items": 0, "days": 0.0})
        slot["items"] += 1
        slot["days"] = round(slot["days"] + e.total_days, 2)

    path = _critical_path(items, {e.item_id: e.total_days for e in estimates})
    effective_team = max(1, min(team_size, len(by_role) or 1))
    elapsed = max(with_contingency / effective_team, path["days"])

    return {
        "ok": True,
        "totals": {
            "manual_days": round(manual, 1),
            "engineering_days": round(total - review, 1),
            "review_days": round(review, 1),
            "total_days": round(total, 1),
            "with_contingency_days": round(with_contingency, 1),
            "saved_days": round(saved, 1),
            "contingency": contingency,
        },
        "duration": {
            "team_size": effective_team,
            "elapsed_days": round(elapsed, 1),
            "elapsed_weeks": round(elapsed / working_days_per_week, 1),
            "critical_path_days": path["days"],
            "critical_path": path["path"],
        },
        "automation": {
            "coverage": round(coverage, 3),
            "coverage_pct": round(coverage * 100, 1),
            "by_class": by_automation,
            "basis": ("Calculated from published baselines and complexity multipliers. "
                      "An estimate, not a guarantee (spec §24)."),
        },
        "by_role": dict(sorted(by_role.items(), key=lambda kv: -kv[1])),
        "items": [e.to_dict() for e in estimates],
    }


def _critical_path(items: List[WorkItem], days: Dict[str, float]) -> Dict[str, Any]:
    """Longest dependency chain. Cycles are ignored rather than hanging."""
    by_id = {i.id: i for i in items}
    memo: Dict[str, tuple] = {}

    def longest(item_id: str, seen: frozenset) -> tuple:
        if item_id in memo:
            return memo[item_id]
        if item_id in seen or item_id not in by_id:
            return (0.0, [])
        best_len, best_path = 0.0, []
        for dep in by_id[item_id].depends_on:
            length, path = longest(dep, seen | {item_id})
            if length > best_len:
                best_len, best_path = length, path
        result = (best_len + days.get(item_id, 0.0), best_path + [item_id])
        memo[item_id] = result
        return result

    best = max((longest(i.id, frozenset()) for i in items), key=lambda r: r[0], default=(0.0, []))
    return {"days": round(best[0], 1), "path": best[1]}


def work_items_from_project(requirements: List[dict], sources: int = 0,
                            entities: int = 0, reports: int = 0,
                            complexity: Optional[Complexity] = None) -> List[WorkItem]:
    """Derive a default work breakdown from the canonical model.

    Counts come from persisted evidence, so the estimate moves when the project
    does. Quantities of zero are simply omitted.
    """
    cx = complexity or Complexity()
    items: List[WorkItem] = [
        WorkItem("WI-DISC", "Discovery workshops", "discovery_workshop", 2, cx),
        WorkItem("WI-REQ", "Requirements definition", "requirement",
                 max(1, len(requirements)), cx, depends_on=["WI-DISC"]),
    ]
    if sources:
        items.append(WorkItem("WI-SRC", "Source system onboarding", "source_system",
                              sources, cx, depends_on=["WI-REQ"]))
    if entities:
        items.append(WorkItem("WI-MODEL", "Data modelling", "data_entity",
                              entities, cx, depends_on=["WI-REQ"]))
        items.append(WorkItem("WI-PIPE", "Pipeline build", "pipeline",
                              entities, cx, depends_on=["WI-MODEL"]))
        items.append(WorkItem("WI-DQ", "Data quality rules", "data_quality_rule",
                              entities * 3, cx, depends_on=["WI-PIPE"]))
    if reports:
        items.append(WorkItem("WI-SEM", "Semantic model", "semantic_model", 1, cx,
                              depends_on=["WI-PIPE"] if entities else ["WI-REQ"]))
        items.append(WorkItem("WI-RPT", "Reports and dashboards", "report",
                              reports, cx, depends_on=["WI-SEM"]))
    items.append(WorkItem("WI-ENV", "Environment setup", "environment", 2, cx))
    items.append(WorkItem("WI-GOV", "Governance controls", "governance_control", 4, cx,
                          depends_on=["WI-REQ"]))
    items.append(WorkItem("WI-TEST", "Test suites", "test_suite",
                          max(1, entities or 2), cx,
                          depends_on=["WI-PIPE"] if entities else ["WI-REQ"]))
    return items
