"""SOW and commercial factory (spec §26, §27).

Assembled **deterministically from the canonical model**, not generated by a
language model. A Statement of Work is a contractual document: every clause must
be traceable to a requirement, an assumption or an explicit unknown, and nothing
may be invented.

Where information is missing the section says so explicitly rather than
producing plausible filler — an SOW that quietly invents scope is a commercial
liability (§68).
"""
from __future__ import annotations

from datetime import date, timedelta
from typing import Any, Dict, List, Optional

SECTIONS = [
    "executive_summary", "business_context", "objectives", "scope", "out_of_scope",
    "use_cases", "solution", "architecture", "data_scope", "ai_scope", "bi_scope",
    "application_scope", "security", "governance", "testing", "deployment",
    "support", "assumptions", "dependencies", "risks", "deliverables",
    "milestones", "acceptance_criteria", "roles", "effort", "commercial_inputs",
    "change_control", "sign_off",
]

_MISSING = "Not yet established. Requires customer input before this SOW can be issued."


def _texts(statements: List[dict], kind: str, limit: int = 40) -> List[str]:
    return [s["text"] for s in statements if s.get("kind") == kind][:limit]


def _or_missing(items: List[str]) -> List[str]:
    return items or [_MISSING]


def build_sow(project: Dict[str, Any], statements: List[Dict[str, Any]],
              estimate_result: Optional[Dict[str, Any]] = None,
              architecture: Optional[Dict[str, Any]] = None,
              start_date: Optional[date] = None) -> Dict[str, Any]:
    """Assemble the SOW. Returns sections plus a completeness report."""
    est = estimate_result or {}
    totals = est.get("totals", {})
    duration = est.get("duration", {})

    requirements = _texts(statements, "requirement")
    objectives = _texts(statements, "objective")
    assumptions = _texts(statements, "assumption")
    risks = _texts(statements, "risk")
    unknowns = _texts(statements, "unknown")
    constraints = _texts(statements, "constraint")

    name = project.get("name", "Engagement")
    domain = project.get("domain") or "unspecified"
    intent = project.get("intent") or _MISSING

    weeks = duration.get("elapsed_weeks")
    days = totals.get("with_contingency_days")

    sections: Dict[str, Any] = {
        "executive_summary": (
            f"{name} delivers the outcomes described by the customer's stated intent, "
            f"in the {domain} domain. "
            + (f"The engagement is estimated at {days} person-days over approximately "
               f"{weeks} weeks." if days else
               "Effort has not yet been estimated; run the estimation stage before issuing this SOW.")
        ),
        "business_context": intent,
        "objectives": _or_missing(objectives),
        "scope": _or_missing(requirements),
        "out_of_scope": [
            "Any requirement not listed in Scope.",
            "Source systems not identified during Discovery.",
            "Production data migration beyond the agreed cutover window.",
            "Licence procurement for third-party platforms.",
        ],
        "use_cases": _or_missing(_texts(statements, "use_case") or objectives),
        "solution": (architecture or {}).get("summary") or _MISSING,
        "architecture": (architecture or {}).get("components") or [_MISSING],
        "data_scope": _or_missing(_texts(statements, "source")),
        "ai_scope": _or_missing(_texts(statements, "ai_use_case")),
        "bi_scope": _or_missing(_texts(statements, "metric")),
        "application_scope": _or_missing(_texts(statements, "application")),
        "security": _or_missing(_texts(statements, "security_requirement")),
        "governance": [
            "All generated artifacts are versioned and evidence-linked.",
            "Human approval is required before any production-affecting change.",
            "An immutable audit trail is maintained for every decision.",
        ],
        "testing": [
            "Unit and integration testing of all delivered components.",
            "Data quality and reconciliation gates prior to promotion.",
            "User acceptance testing against the acceptance criteria in this SOW.",
        ],
        "deployment": [
            "Deployment follows PLAN -> REVIEW -> APPROVE -> EXECUTE -> VALIDATE.",
            "No destructive operation is performed without recorded human approval.",
        ],
        "support": "Hypercare period and ongoing support to be agreed prior to go-live.",
        "assumptions": _or_missing(assumptions),
        "dependencies": _or_missing(constraints + [
            "Timely customer access to source systems and subject-matter experts.",
            "Customer-provided environment and credentials where applicable.",
        ]),
        "risks": _or_missing(risks),
        "deliverables": _deliverables(est),
        "milestones": _milestones(duration, start_date),
        "acceptance_criteria": [
            f"Each requirement in Scope is demonstrably satisfied ({len(requirements)} requirements).",
            "All quality gates pass and evidence is recorded.",
            "Handover documentation is delivered and accepted.",
        ],
        "roles": _roles(est),
        "effort": {
            "total_days": totals.get("total_days"),
            "with_contingency_days": days,
            "review_days": totals.get("review_days"),
            "manual_baseline_days": totals.get("manual_days"),
            "automation_saving_days": totals.get("saved_days"),
            "automation_coverage_pct": est.get("automation", {}).get("coverage_pct"),
            "basis": est.get("automation", {}).get("basis", ""),
        } if totals else _MISSING,
        "commercial_inputs": _commercial(est),
        "change_control": (
            "Any change to Scope is raised as a Change Request, assessed for downstream "
            "impact across architecture, engineering, testing, effort and timeline, and "
            "requires written approval from both parties before work proceeds."
        ),
        "sign_off": {
            "customer": {"name": "", "role": "", "date": ""},
            "supplier": {"name": "", "role": "", "date": ""},
            "note": "This SOW is not valid until signed by both parties.",
        },
    }

    completeness = _completeness(sections, unknowns)
    return {
        "project": name,
        "generated_from_project_version": project.get("version"),
        "sections": sections,
        "open_questions": unknowns,
        "completeness": completeness,
        "issuable": completeness["ready"],
        "generation_mode": "deterministic_from_canonical_model",
    }


def _deliverables(est: Dict[str, Any]) -> List[str]:
    base = ["Discovery report", "Current-state assessment", "Requirements catalogue",
            "Target architecture and platform decision", "Data design and metadata",
            "Engineering plan and generated components", "Test plan and evidence",
            "Deployment plan", "Handover pack"]
    roles = est.get("by_role", {})
    if "BI Developer" in roles:
        base.insert(5, "Semantic model and reports")
    if "AI Engineer" in roles:
        base.insert(5, "AI/ML design and evaluation")
    return base


def _milestones(duration: Dict[str, Any], start: Optional[date]) -> List[dict]:
    """Spread milestones across the estimated elapsed duration."""
    weeks = duration.get("elapsed_weeks")
    if not weeks:
        return [{"name": "Milestones pending estimation", "week": None, "date": None}]
    start = start or date.today()
    plan = [("Discovery complete", 0.12), ("Assessment and requirements approved", 0.25),
            ("Architecture and platform approved", 0.40), ("Engineering complete", 0.70),
            ("Testing complete", 0.85), ("Deployment and handover", 1.0)]
    out = []
    for label, fraction in plan:
        week = max(1, round(weeks * fraction))
        out.append({"name": label, "week": week,
                    "date": (start + timedelta(weeks=week)).isoformat()})
    return out


def _roles(est: Dict[str, Any]) -> List[dict]:
    by_role = est.get("by_role", {})
    if not by_role:
        return [{"role": _MISSING, "days": None}]
    return [{"role": r, "days": d} for r, d in by_role.items()]


def _commercial(est: Dict[str, Any]) -> Dict[str, Any]:
    """Pricing *inputs* only. Never a committed price (spec §27)."""
    by_role = est.get("by_role", {})
    return {
        "effort_by_role_days": by_role,
        "rate_card": {r: None for r in by_role} or _MISSING,
        "platform_costs": _MISSING,
        "llm_usage_costs": _MISSING,
        "third_party_services": _MISSING,
        "contingency_pct": round(est.get("totals", {}).get("contingency", 0) * 100, 1)
        if est.get("totals") else None,
        "note": ("Commercial inputs only. Rates, platform costs and margin are supplied "
                 "by the commercial team; this platform does not set or commit pricing."),
    }


def _completeness(sections: Dict[str, Any], unknowns: List[str]) -> Dict[str, Any]:
    """Report which sections still contain placeholders (spec §68)."""
    incomplete = []
    for key, value in sections.items():
        if value == _MISSING:
            incomplete.append(key)
        elif isinstance(value, list) and value == [_MISSING]:
            incomplete.append(key)
    return {
        "total_sections": len(sections),
        "incomplete_sections": incomplete,
        "complete_count": len(sections) - len(incomplete),
        "open_questions": len(unknowns),
        "ready": not incomplete and not unknowns,
        "reason": ("Ready to issue." if not incomplete and not unknowns else
                   f"{len(incomplete)} section(s) incomplete and {len(unknowns)} open "
                   f"question(s) outstanding."),
    }


def render_markdown(sow: Dict[str, Any]) -> str:
    """Human-readable SOW, used for PDF/DOCX generation (§29)."""
    out: List[str] = [f"# Statement of Work — {sow['project']}", ""]
    if not sow.get("issuable"):
        out += [f"> **DRAFT — not issuable.** {sow['completeness']['reason']}", ""]
    for key in SECTIONS:
        value = sow["sections"].get(key)
        if value is None:
            continue
        out.append(f"## {key.replace('_', ' ').title()}")
        if isinstance(value, str):
            out.append(value)
        elif isinstance(value, list):
            for item in value:
                out.append(f"- {item}" if not isinstance(item, dict)
                           else f"- {', '.join(f'{k}: {v}' for k, v in item.items() if v)}")
        elif isinstance(value, dict):
            for k, v in value.items():
                out.append(f"- **{k}**: {v}")
        out.append("")
    if sow.get("open_questions"):
        out += ["## Open Questions — Customer Input Required", ""]
        out += [f"- {q}" for q in sow["open_questions"]]
    return "\n".join(out)
