'use client';
/** Knowledge Center — every artifact the platform has generated, browsable. */
import {useEffect, useState} from 'react';
import {BookOpen, RefreshCw, Layers3, FileJson} from 'lucide-react';
import {getEngagements, getArtifacts} from '../../lib/api';
import {useEngagement} from '../../lib/engagement-context';
import {ArtifactViewer, kindLabel} from '../../components/ArtifactViewer';
import {AcceleratorCatalogue} from '../../components/AcceleratorCatalogue';

export default function KnowledgePage() {
  const {engagementId, engagements, select} = useEngagement();
  const [counts, setCounts] = useState<Record<string, number>>({});
  const [loading, setLoading] = useState(false);

  // Portfolio-wide artifact index across every engagement.
  const load = async () => {
    setLoading(true);
    try {
      const list = (await getEngagements()).items || [];
      const acc: Record<string, number> = {};
      const results = await Promise.allSettled(list.map(e => getArtifacts(e.id)));
      results.forEach(r => {
        if (r.status !== 'fulfilled') return;
        (r.value.items || []).forEach(a => { acc[a.kind] = (acc[a.kind] || 0) + 1; });
      });
      setCounts(acc);
    } finally { setLoading(false); }
  };

  useEffect(() => { load(); }, []);

  const kinds = Object.entries(counts).sort((a, b) => b[1] - a[1]);

  return (
    <>
      <div className="pageHead">
        <div>
          <div className="crumb">Home <span>›</span> Knowledge Center</div>
          <h1>Knowledge Center</h1>
          <p>Reusable patterns, architecture decisions and delivery evidence across the entire portfolio.</p>
        </div>
        <div className="headActions">
          <button className="secondary" onClick={load} disabled={loading}>
            <RefreshCw size={16} className={loading ? 'spin' : ''} /> Refresh
          </button>
        </div>
      </div>

      <div className="stats">
        <div className="stat">
          <div className="statIcon"><Layers3 size={20} /></div>
          <div className="muted">Engagements</div><strong>{engagements.length}</strong>
          <div className="delta">↗ Portfolio wide</div>
        </div>
        <div className="stat">
          <div className="statIcon"><FileJson size={20} /></div>
          <div className="muted">Artifact types</div><strong>{kinds.length}</strong>
          <div className="delta">↗ Distinct kinds</div>
        </div>
        <div className="stat">
          <div className="statIcon"><BookOpen size={20} /></div>
          <div className="muted">Total artifacts</div>
          <strong>{Object.values(counts).reduce((a, b) => a + b, 0)}</strong>
          <div className="delta">↗ Governed outputs</div>
        </div>
      </div>

      <section className="panel">
        <div className="panelHead"><h3><Layers3 size={18} /> Asset library</h3></div>
        {kinds.length === 0 ? (
          <div className="empty"><BookOpen size={18} /> {loading ? 'Indexing artifacts…' : 'No artifacts generated yet. Run stages to build the knowledge base.'}</div>
        ) : (
          <div className="assessmentGrid">
            {kinds.map(([kind, n]) => (
              <div className="assessmentCard" key={kind}>
                <div className="assessmentCardTop"><strong>{kindLabel(kind)}</strong><span>{n}</span></div>
                <p>Reusable {kindLabel(kind).toLowerCase()} evidence generated by the factory.</p>
              </div>
            ))}
          </div>
        )}
      </section>

      <section className="panel">
        <div className="panelHead"><h3>Browse by engagement</h3></div>
        <div className="chipRow">
          {engagements.map(e => (
            <button key={e.id} className={e.id === engagementId ? 'chipBtn active' : 'chipBtn'} onClick={() => select(e.id)}>
              {e.title}
            </button>
          ))}
        </div>
      </section>

      {engagementId && <ArtifactViewer engagementId={engagementId} title="All artifacts for this engagement" />}

      <AcceleratorCatalogue />
    </>
  );
}
