'use client';
import Link from 'next/link';
import { useMemo, useState } from 'react';
import { ArrowRight, BrainCircuit, Boxes, CheckCircle2, ChevronRight, FileText, GitBranch, Layers3, Radar, ShieldCheck, Sparkles, Target, Workflow, Zap } from 'lucide-react';

type Product = { id:string; code:string; name:string; tagline:string; description:string; stages:string[]; accelerators:string[]; icon:any; href:string; metric:string };

const products:Product[] = [
 {id:'intake',code:'01',name:'Intake & RFP Intelligence',tagline:'Turn ambiguity into an executable engagement.',description:'Ingest RFPs, RFIs, emails, documents and short customer briefs. Extract intent, scope, stakeholders, constraints, risks and the evidence needed for the next action.',stages:['Capture','Discover'],accelerators:['Universal Intake','RFP/RFI Intelligence','Stakeholder & Scope Mining','Evidence Pack Builder'],icon:FileText,href:'/intake',metric:'AI-led intake'},
 {id:'ba',code:'02',name:'Business Analysis Studio',tagline:'BRD → FRD → SRD, generated with traceability.',description:'Convert discovered intent into governed requirements, user journeys, functional and non-functional requirements, assumptions, acceptance criteria and traceable decisions.',stages:['Requirements','Design'],accelerators:['BRD Generator','FRD Generator','SRD / Solution Requirements','Requirements Traceability'],icon:Workflow,href:'/discovery',metric:'Traceable requirements'},
 {id:'discovery',code:'03',name:'Discovery & Assessment',tagline:'Know the current state before designing the future state.',description:'Evidence-driven environment, application, data, maturity and current-state assessment with deterministic scoring and AI reasoning kept separate.',stages:['Assess','Score'],accelerators:['Environment Assessment','Current-State Assessment','Data Quality Profiler','Maturity & Risk Scoring'],icon:Radar,href:'/discovery',metric:'Evidence first'},
 {id:'architecture',code:'04',name:'Architecture & Platform Decision',tagline:'Neutral decisions. Hard constraints. Defensible architecture.',description:'Compare candidate platforms and architectures using AI recommendations, deterministic scoring and customer constraints. Every recommendation carries its evidence and rationale.',stages:['Decide','Architect'],accelerators:['Platform Decision Engine','Target Architecture','Security & Network Blueprint','Governance & Lineage'],icon:Layers3,href:'/factory/platform',metric:'AI + deterministic'},
 {id:'data',code:'05',name:'Data Engineering Factory',tagline:'From source patterns to production-grade pipelines.',description:'Generate metadata, ingestion, CDC, transformation, orchestration and reconciliation assets with reusable engineering patterns and approval gates.',stages:['Metadata','Build'],accelerators:['Metadata Factory','Batch / ETL / ELT','CDC & Incremental Loading','Streaming & Near-Real-Time'],icon:GitBranch,href:'/engineering',metric:'Automation-ready'},
 {id:'ai',code:'06',name:'AI & Analytics Factory',tagline:'Operationalize AI use cases, metrics and intelligence.',description:'Design AI use cases and agents, evaluation harnesses, semantic models, KPI definitions and analytics outputs on the same governed engagement backbone.',stages:['AI','Analytics'],accelerators:['AI Use Case & Agent Design','AI Governance & Evaluation','Semantic Model & Metrics','Document Intelligence'],icon:BrainCircuit,href:'/ai-analytics',metric:'Governed AI'},
 {id:'assure',code:'07',name:'Quality, Validation & Release',tagline:'No claim without evidence. No release without gates.',description:'Validate generated assets, test data quality, reconcile outputs and package deployment evidence. Approval gates remain explicit and auditable.',stages:['Validate','Release'],accelerators:['Data Quality & Reconciliation','Test Strategy & Assurance','CI/CD & Gated Release','Deployment Readiness'],icon:ShieldCheck,href:'/validation',metric:'Evidence-gated'},
 {id:'delivery',code:'08',name:'Delivery & Commercial Control Plane',tagline:'Turn delivery intelligence into a programme system.',description:'Estimate effort, identify automation coverage, generate SOWs, lock scope and keep delivery decisions connected to the same evidence and lifecycle state.',stages:['Estimate','Commercial','Operate'],accelerators:['Effort & Automation Analysis','SOW & Commercial Pack','Scope Lock & Change Control','Operations & Handover'],icon:Target,href:'/factory/estimate',metric:'Programme control'},
];

export function ProductPortfolio(){
 const [filter,setFilter]=useState('All');
 const [open,setOpen]=useState<string|null>(null);
 const filters=['All','Capture','Requirements','Assess','Architect','Build','AI','Validate','Commercial'];
 const visible=useMemo(()=>filter==='All'?products:products.filter(p=>p.stages.some(s=>s.toLowerCase().includes(filter.toLowerCase()))),[filter]);
 return <div className="portfolio">
   <section className="factoryHero">
    <div className="factoryHeroGlow" />
    <div className="eyebrow"><Sparkles size={13}/> ELITEINTELIA AI DATA AUTOMATION FACTORY</div>
    <div className="factoryHeroGrid">
      <div><h1>From <span>RFP to production.</span><br/>One intelligent delivery factory.</h1><p>AI reasoning, deterministic engineering, customer constraints and human approvals unified into one enterprise transformation control plane.</p><div className="heroCtas"><Link className="primary" href="/intake"><Zap size={16}/> Start an engagement</Link><Link className="secondary" href="/knowledge"><Boxes size={16}/> Explore accelerators</Link></div></div>
      <div className="factorySignal"><div className="signalHead"><span className="liveDot"/> FACTORY ORCHESTRATION</div><div className="signalFlow"><b>Intent</b><ChevronRight/><b>Requirements</b><ChevronRight/><b>Architecture</b><ChevronRight/><b>Engineering</b><ChevronRight/><b>Release</b></div><div className="signalFooter"><CheckCircle2 size={15}/> Evidence + traceability + approval gates at every transition</div></div>
    </div>
   </section>
   <section className="portfolioToolbar"><div><div className="sectionKicker">PRODUCT FACTORY</div><h2>Eight productized capabilities. One governed backbone.</h2><p>Each product ships with dedicated accelerators and plugs into the same engagement lifecycle.</p></div><div className="filterBar">{filters.map(f=><button key={f} className={filter===f?'active':''} onClick={()=>setFilter(f)}>{f}</button>)}</div></section>
   <section className="productGrid">{visible.map(p=>{const Icon=p.icon; const isOpen=open===p.id; return <article className={`productCard ${isOpen?'open':''}`} key={p.id}><div className="productTop"><div className="productIcon"><Icon size={20}/></div><span className="productCode">{p.code}</span><span className="productMetric">{p.metric}</span></div><h3>{p.name}</h3><strong>{p.tagline}</strong><p>{p.description}</p><div className="stagePills">{p.stages.map(s=><span key={s}>{s}</span>)}</div><div className="acceleratorHeader"><span><Boxes size={14}/> {p.accelerators.length} accelerators</span><button onClick={()=>setOpen(isOpen?null:p.id)}>{isOpen?'Hide':'View'}<ChevronRight size={14}/></button></div>{isOpen&&<div className="acceleratorList">{p.accelerators.map((a,i)=><div key={a}><span>{String(i+1).padStart(2,'0')}</span><b>{a}</b><CheckCircle2 size={14}/></div>)}</div>}<Link className="productLink" href={p.href}>Open product workspace <ArrowRight size={15}/></Link></article>})}</section>
   <section className="operatingModel"><div><div className="sectionKicker">THE ELITEINTELIA DIFFERENTIATOR</div><h2>AI recommends. Engines score. Constraints decide. Humans approve.</h2><p>The factory separates probabilistic reasoning from deterministic controls, then records the evidence behind every material recommendation and delivery transition.</p></div><div className="modelSteps"><div><span>01</span><b>AI reasoning</b><small>Extract, infer, propose</small></div><div><span>02</span><b>Deterministic scoring</b><small>Calculate, validate, reproduce</small></div><div><span>03</span><b>Customer constraints</b><small>Enforce hard boundaries</small></div><div><span>04</span><b>Human approval</b><small>Govern release decisions</small></div></div></section>
 </div>
}
