"""Next Best Action: what should happen next, and why.

The recommendation must be reproducible. A delivery instruction that changes
between two identical runs cannot be defended to a customer, so this is
calculated from lifecycle gates, approvals and recorded provenance — never
generated by a model.
"""
from dataclasses import dataclass

from core.domain.lifecycle import LifecycleState, StageStatus
from core.next_action import evidence_completeness, recommend


@dataclass
class S:
    kind: str
    provenance: str


def _complete(*stage_ids, approvals=None):
    return LifecycleState(
        statuses={s: StageStatus.COMPLETE for s in stage_ids},
        approvals=approvals or {})


# ------------------------------------------------------------- prioritisation
def test_an_empty_engagement_asks_for_evidence_first():
    out = recommend(LifecycleState(), [], evidence_count=0)

    assert out["state"] == "AWAITING EVIDENCE"
    assert out["primary"]["kind"] == "collect_evidence"
    assert out["primary"]["owner"] == "Business Analyst"


def test_an_approval_gate_outranks_running_more_stages():
    """Generating further work on unapproved output only deepens the problem."""
    state = _complete("intent", "evidence", "discovery", "questions",
                      "assessment", "requirements")
    out = recommend(state, [], evidence_count=1)

    assert out["state"] == "AWAITING APPROVAL"
    assert out["primary"]["kind"] == "approve"
    assert out["primary"]["stage_id"] == "requirements"
    # It must say what the gate is holding up, not merely that it exists.
    assert "Platform Selection" in out["primary"]["why"]


def test_the_next_runnable_stage_is_recommended_when_nothing_is_gated():
    out = recommend(_complete("intent", "evidence"), [], evidence_count=1)

    assert out["primary"]["kind"] == "run_stage"
    assert out["primary"]["stage_id"] == "discovery"
    assert out["primary"]["automatable"] is True


def test_blocked_stages_state_what_would_release_them():
    out = recommend(_complete("intent", "evidence"), [], evidence_count=1)
    blocked = [a for a in out["actions"] if a["kind"] == "blocked"]

    assert blocked, "the operator should not have to infer blockers"
    assert all(a["blocked_by"] for a in blocked)


def test_every_action_names_an_owner():
    """A recommendation nobody owns does not get done."""
    for state in (LifecycleState(), _complete("intent", "evidence"),
                  _complete("intent", "evidence", "discovery")):
        for action in recommend(state, [], evidence_count=1)["actions"]:
            assert action["owner"], f"no owner on {action['id']}"


# ------------------------------------------------------------- completeness
def test_completeness_counts_evidenced_statements_not_opinions():
    statements = [S("requirement", "FACT"), S("requirement", "FACT"),
                  S("objective", "CUSTOMER_DECISION"),
                  S("question", "UNKNOWN"), S("risk", "AI_INFERENCE")]

    c = evidence_completeness(statements)
    assert c["evidenced"] == 3
    assert c["open_questions"] == 1
    assert c["percent"] == 60


def test_completeness_is_zero_rather_than_invented_when_nothing_is_known():
    assert evidence_completeness([])["percent"] == 0


def test_open_question_count_reads_correctly_when_there_is_one():
    out = recommend(_complete("intent", "evidence", "discovery"),
                    [S("question", "UNKNOWN")], evidence_count=1)
    titles = " ".join(a["title"] for a in out["actions"])

    assert "1 open question" in titles
    assert "1 open questions" not in titles


# ------------------------------------------------------------ reproducibility
def test_the_same_state_always_yields_the_same_recommendation():
    state = _complete("intent", "evidence", "discovery")
    statements = [S("requirement", "FACT"), S("question", "UNKNOWN")]

    first = recommend(state, statements, evidence_count=2)
    second = recommend(state, statements, evidence_count=2)
    assert first == second
    assert "deterministic" in first["basis"]


# ------------------------------------------------------------------- endpoint
def test_the_endpoint_serves_a_recommendation(tmp_path, monkeypatch):
    import importlib
    import os

    monkeypatch.setenv("DATABASE_URL", f"sqlite:///{tmp_path / 'na.db'}")
    monkeypatch.setenv("LLM_PROVIDERS", "")
    for key in [k for k in os.environ
                if k.startswith(("ELITEINTELIA_", "CAPGEMINI_"))]:
        monkeypatch.delenv(key, raising=False)

    from persistence import repository as R
    R.reset_engine()
    R.init_db()
    import core.api_v2 as api_v2
    importlib.reload(api_v2)

    from fastapi import FastAPI
    from fastapi.testclient import TestClient
    app = FastAPI()
    app.include_router(api_v2.router)
    c = TestClient(app)

    pid = c.post("/api/v2/projects", json={"name": "P", "intent": "Automate."}).json()["id"]
    d = c.get(f"/api/v2/projects/{pid}/next-action").json()

    assert d["primary"]["kind"] == "collect_evidence"
    assert d["progress"]["total"] == 20

    assert c.get("/api/v2/projects/does-not-exist/next-action").status_code == 404
    R.reset_engine()
