'use client';
import {useEffect,useState} from 'react';
import {ArrowRight,CheckCircle2,CloudCog,ShieldCheck} from 'lucide-react';
import {getEngagement,savePlatform,verifyPlatform,platformPlan} from '../../lib/api';
const platforms=['Databricks','Microsoft Fabric','Snowflake','BigQuery','Amazon Redshift','Azure Synapse','Azure SQL','Other'];
// Free text here produced values like "azure ", "MS Azure" and "Azure/AWS",
// which the platform-fit engine could not match against its cloud catalogue.
const clouds=['Azure','AWS','Google Cloud','On-premises','Hybrid','Multi-cloud','Not decided'];
const regionsByCloud:Record<string,string[]>={
 'Azure':['uaenorth','westeurope','northeurope','eastus','uksouth','centralindia','Other'],
 'AWS':['me-central-1','eu-west-1','eu-central-1','us-east-1','ap-south-1','Other'],
 'Google Cloud':['europe-west1','us-central1','asia-south1','Other'],
 'On-premises':['Primary data centre','Secondary data centre','Other'],
 'Hybrid':['Other'],'Multi-cloud':['Other'],'Not decided':['Other']};
export default function PlatformPage(){
 const [id]=useState<string|null>(()=>typeof window!=='undefined'?new URLSearchParams(window.location.search).get('engagement')||localStorage.getItem('eliteintelia_engagement'):null);
 const [eng,setEng]=useState<any>(null); const [form,setForm]=useState<any>({platform:'Databricks',cloud:'Azure',environment_mode:'existing',endpoint:'',credential_ref:'',auth_method:'OAuth / Service Principal',environment_name:'',region:'',decision_status:'selected'}); const [msg,setMsg]=useState(''); const [busy,setBusy]=useState(false);
 const load=async()=>{if(!id)return;const x=await getEngagement(id);setEng(x);if(x.project.platform_config&&Object.keys(x.project.platform_config).length)setForm((f:any)=>({...f,...x.project.platform_config}))};
 useEffect(()=>{load().catch(()=>{})},[id]);
 const save=async()=>{if(!id)return;setBusy(true);try{const r=await savePlatform(id,form);setMsg(`Platform saved: ${r.state?.label||'configuration updated'}.`);await load()}catch(e:any){setMsg(e.message||'Unable to save platform.')}finally{setBusy(false)}};
 const verify=async()=>{if(!id)return;setBusy(true);try{const r=await verifyPlatform(id);setMsg(r.state?.state==='VERIFIED'?'Customer platform verified. Environment Assessment can now be refreshed.':r.state?.next_action||'Verification completed.');await load()}catch(e:any){setMsg(e.message||'Platform verification failed.')}finally{setBusy(false)}};
 const plan=async()=>{if(!id)return;setBusy(true);try{const r=await platformPlan(id);setMsg(r.error||'Platform provisioning plan generated.');await load()}catch(e:any){setMsg(e.message||'Unable to generate plan.')}finally{setBusy(false)}};
 const state=eng?.project?.platform_config?.verified_at?'VERIFIED':eng?.project?.platform_config?.decision_status?'SELECTED':'NOT_SELECTED';
 return <>
  <div className="pageHead"><div><div className="crumb">Home <span>›</span> Platform & Environment {eng&&<><span>›</span>{eng.project.name}</>}</div><h1>Platform & Environment</h1><p>Confirm the governed target platform and establish customer-environment evidence before engineering.</p></div></div>
  {!eng?<div className="panel emptyLarge"><h3>No engagement selected</h3><p>Open Platform & Environment with <code>?engagement=&lt;id&gt;</code>.</p></div>:<>
   <div className="workspaceGrid"><div className="panel"><div className="panelTitle"><CloudCog/> Target platform decision</div><label className="fieldLabel">Target platform</label><select className="textInput" value={form.platform} onChange={e=>setForm({...form,platform:e.target.value})}>{platforms.map(x=><option key={x}>{x}</option>)}</select><label className="fieldLabel">Cloud</label><select className="textInput" value={form.cloud||''} onChange={e=>setForm({...form,cloud:e.target.value,region:''})}><option value="">Select a cloud…</option>{clouds.map(c=><option key={c} value={c}>{c}</option>)}</select>{form.cloud&&<><label className="fieldLabel">Region</label><select className="textInput" value={form.region||''} onChange={e=>setForm({...form,region:e.target.value})}><option value="">Select a region…</option>{(regionsByCloud[form.cloud]||['Other']).map(r=><option key={r} value={r}>{r}</option>)}</select></>}<label className="fieldLabel">Environment mode</label><select className="textInput" value={form.environment_mode||'existing'} onChange={e=>setForm({...form,environment_mode:e.target.value})}><option value="existing">Existing customer environment</option><option value="provision">Customer cloud provisioning / IaC</option></select><button className="primary" onClick={save} disabled={busy}>Save Platform Decision</button></div>
   <div className="panel"><div className="panelTitle"><ShieldCheck/> Customer environment onboarding</div>{form.environment_mode==='existing'?<><label className="fieldLabel">Customer endpoint</label><input className="textInput" value={form.endpoint||''} onChange={e=>setForm({...form,endpoint:e.target.value})} placeholder="https://<customer-endpoint>"/><label className="fieldLabel">Credential reference — secret name only</label><input className="textInput" value={form.credential_ref||''} onChange={e=>setForm({...form,credential_ref:e.target.value})} placeholder="CINVENT_CUSTOMER_DATABRICKS_CREDENTIAL"/><label className="fieldLabel">Authentication method</label><input className="textInput" value={form.auth_method||''} onChange={e=>setForm({...form,auth_method:e.target.value})}/><button className="secondary" onClick={verify} disabled={busy}>Verify Customer Environment</button></>:<><p>Provisioning mode requires a customer-owned cloud scope, region, deployment identity and approved IaC plan.</p><button className="secondary" onClick={plan} disabled={busy}>Generate Provisioning Plan</button></>}</div></div>
   {msg&&<div className="notice"><CheckCircle2 size={18}/>{msg}</div>}
   <div className="panel"><div className="panelTitle"><ShieldCheck/> Gate status</div><div className="statusRow"><span>Platform</span><b>{form.platform}</b></div><div className="statusRow"><span>Onboarding state</span><b className={state==='VERIFIED'?'ok':'pending'}>{state}</b></div><div className="statusRow"><span>Blueprint approval</span><b className={eng.lifecycle.approvals.blueprint?'ok':'pending'}>{eng.lifecycle.approvals.blueprint?'APPROVED':'REQUIRED'}</b></div><div className="statusRow"><span>Engineering</span><b className={eng.lifecycle.gates?.engineering_ready&&eng.lifecycle.gates?.platform_ready?'ok':'pending'}>{eng.lifecycle.gates?.engineering_ready&&eng.lifecycle.gates?.platform_ready?'READY':'BLOCKED UNTIL GATES PASS'}</b></div>{state==='VERIFIED'&&<a className="primary" href={`/engineering?engagement=${encodeURIComponent(eng.project.id)}`}><ArrowRight size={17}/> Continue to Engineering</a>}</div>
  </>}
 </>;
}
