'use client';
/**
 * Next Best Action.
 *
 * A twenty-stage lifecycle presented as twenty buttons makes the operator work
 * out what is runnable, what is blocked and who has to act. This panel states
 * it: one recommended step, the reason it is recommended, and who owns it.
 *
 * Everything shown is calculated by the backend from lifecycle gates,
 * approvals and recorded provenance — never generated by a model, so the same
 * engagement state always yields the same recommendation.
 */
import {Compass, CircleCheck, Lock, MessageCircleQuestion, Upload, Play} from 'lucide-react';

export type NextAction = {
  id: string; title: string; why: string; owner: string; kind: string;
  stage_id?: string; automatable?: boolean; blocked_by?: string[];
};
export type NextActionPayload = {
  state: string;
  progress: {complete: number; total: number};
  evidence: {documents: number; percent: number; evidenced: number;
             open_questions: number; total: number};
  primary: NextAction | null;
  actions: NextAction[];
  basis: string;
};

const ICON: Record<string, any> = {
  collect_evidence: Upload, run_stage: Play, approve: CircleCheck,
  answer_questions: MessageCircleQuestion, blocked: Lock,
};

export function NextBestAction(
  {data, onRun}: {data?: NextActionPayload | null; onRun?: (stageId: string) => void},
) {
  if (!data || !data.primary) return null;
  const p = data.primary;
  const Icon = ICON[p.kind] || Compass;
  const rest = data.actions.filter(a => a.id !== p.id);

  return (
    <section className="nba">
      <header>
        <Compass size={15} />
        <h3>Next best action</h3>
        <span className="nbaState">{data.state}</span>
      </header>

      <div className="nbaPrimary">
        <div className="nbaIcon"><Icon size={17} /></div>
        <div>
          <strong>{p.title}</strong>
          <p>{p.why}</p>
          <div className="nbaMeta">
            <span className="nbaOwner">{p.owner}</span>
            {p.automatable && <span className="nbaAuto">the platform can run this</span>}
          </div>
          {p.kind === 'run_stage' && p.stage_id && onRun && (
            <button className="sm" onClick={() => onRun(p.stage_id!)}>
              <Play size={13} /> Run {p.title.replace(/^Run /, '')}
            </button>
          )}
        </div>
      </div>

      <div className="nbaStats">
        <div><b>{data.progress.complete}/{data.progress.total}</b><span>stages complete</span></div>
        <div><b>{data.evidence.documents}</b><span>documents</span></div>
        <div><b>{data.evidence.percent}%</b><span>evidence-backed</span></div>
        <div><b>{data.evidence.open_questions}</b><span>open questions</span></div>
      </div>

      {rest.length > 0 && (
        <ul className="nbaThen">
          {rest.map(a => {
            const I = ICON[a.kind] || Compass;
            return (
              <li key={a.id} className={a.kind === 'blocked' ? 'isBlocked' : ''}>
                <I size={12} />
                <span className="nbaThenTitle">{a.title}</span>
                <span className="nbaThenWhy">{a.why}</span>
                <em>{a.owner}</em>
              </li>
            );
          })}
        </ul>
      )}

      <footer title={data.basis}>Calculated from lifecycle gates, approvals and recorded provenance — not model-generated.</footer>
    </section>
  );
}
